all:
  vars:
    ansible_connection: ssh
    ansible_user: kube
    ansible_ssh_pass: kube
    ansible_ssh_private_key_file: /root/.ssh/id_rsa

master:
  hosts:
    10.128.0.33:

worker:
  hosts:
    10.128.0.34:
    10.128.0.35:
