all:
  vars:
    ansible_connection: ssh
    ansible_user: kube
    ansible_ssh_pass: kube
    ansible_ssh_private_key_file: /root/.ssh/id_rsa

master:
  hosts:
    <master-ip>:

worker:
  hosts:
    <worker-1-ip>:
    <worker-2-ip>:
