all:
  vars:
    ansible_connection: ssh
    ansible_user: kube
    ansible_ssh_pass: kube
    ansible_ssh_private_key_file: /root/.ssh/id_rsa

master:
  hosts:
    10.128.0.30:

worker:
  hosts:
    10.128.0.31:
    10.128.0.32:
