- name: Disable SELinux
  become: true
  selinux:
    state: disabled

- name: Add Kubernetes repository
  become: true
  yum_repository:
    file: kubernetes
    name: Kubernetes
    description: Kubernetes YUM repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install Kubernetes packages
  become: true
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker
    - kubelet
    - kubeadm
    - kubernetes-cni

- name: Set Docker logging-driver
  become: true
  replace:
    path: /etc/sysconfig/docker
    regexp: 'journald'
    replace: 'json-file'
 
- name: Start the Docker service
  become: true
  service:
    name: docker
    state: started

- name: Start the Kubelet service
  become: true
  service:
    name: kubelet
    state: started

- name: Enable the Docker service
  become: true
  systemd:
    name: docker
    enabled: yes

- name: Enable the Kubelet service
  become: true
  systemd:
    name: kubelet
    enabled: yes

- name: Remove swapfile from /etc/fstab
  become: true
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  become: true
  command: swapoff -a

- name: Set iptables value
  become: true
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes

- name: Edit k8s.conf file
  become: true
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: net.bridge.bridge-nf-call-iptables=1
    create: yes
