- name: Install kubectl package
  become: true
  yum:
    name: kubectl
    state: present
    update_cache: yes

- name: kubeadm init
  become: true
  command: kubeadm init

- name: Create the directory for config file
  become: true
  file:
    path: /home/kube/.kube
    state: directory
    owner: kube
    group: kube
    mode: '0775'

- name: Copy the config file
  become: true
  command: cp -i /etc/kubernetes/admin.conf /home/kube/.kube/config

- name: Set permissions for config file
  become: true
  file:
    path: /home/kube/.kube/config
    owner: kube
    group: kube
    mode: '0600'

- name: Setup weavenet pod network
  become: false
  command: kubectl apply -f "https://cloud.weave.works/k8s/v1.16/net.yaml"

- name: Generate join command
  become: true
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to file
  become: true
  copy:
    content: "{{ join_command.stdout_lines[0] }}"
    dest: /home/kube/joincommand.sh

- name: Copy join command to ansible host
  become: true
  fetch:
    src: /home/kube/joincommand.sh
    dest: /home/kube/
    flat: yes
