- name: Initialize the Kubernetes cluster using kubeadm
  hosts: master
  become: true
  tasks:
  - name: kubeadm init
    command: kubeadm init

- name: Setup kubeconfig for user
  hosts: master
  become: true
  tasks:
  - name: Create the directory
    file:
      path: /home/kube/.kube
      state: directory
      owner: kube
      group: kube
      mode: '0775'
  - name: Copy the config file
    command: cp -i /etc/kubernetes/admin.conf /home/kube/.kube/config
  - name: Set permissions for config file
    file:
      path: /home/kube/.kube/config
      owner: kube
      group: kube
      mode: '0600'

- name: Setup weavenet pod network
  hosts: master
  become: false
  tasks:
  - name: Setup weavenet pod network
    command: kubectl apply -f "https://cloud.weave.works/k8s/v1.16/net.yaml"
