- name: Disable SELinux
  hosts: all
  become: true
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled

- name: Add Kubernetes repository
  hosts: all
  become: true
  tasks:
  - name: Add Kubernetes repository
    yum_repository:
      file: kubernetes
      name: Kubernetes
      description: Kubernetes YUM repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install Kubernetes packages
  hosts: all
  become: true
  tasks:
  - name: Install Kubernetes packages
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker
      - kubelet
      - kubeadm
      - kubernetes-cni

- name: Install kubectl package
  hosts: master
  become: true
  tasks:
  - name: Install kubectl package
    yum:
      name: kubectl
      state: present
      update_cache: yes

- name: Edit the Docker configuration
  hosts: all
  become: true
  tasks:
  - name: Set Docker logging-driver
    replace:
      path: /etc/sysconfig/docker
      regexp: 'journald'
      replace: 'json-file'
 
- name: Start the Kubernetes services
  hosts: all
  become: true
  tasks:
  - name: Start the Docker service
    service:
      name: docker
      state: started
  - name: Start the Kubelet service
    service:
      name: kubelet
      state: started

- name: Enable the Kubernetes services
  hosts: all
  become: true
  tasks:
  - name: Enable the Docker service
    systemd:
      name: docker
      enabled: yes
  - name: Enable the Kubelet service
    systemd:
      name: kubelet
      enabled: yes

- name: Remove swapfile and disable swap
  hosts: all
  become: true
  tasks:
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none
  - name: Disable swap
    command: swapoff -a

- name: Update iptables
  hosts: all
  become: true
  tasks:
  - name: Set value
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      sysctl_set: yes
  - name: Edit file
    lineinfile:
      path: /etc/sysctl.d/k8s.conf
      line: net.bridge.bridge-nf-call-iptables=1
      create: yes
