- name: Generate join command
  hosts: master
  become: true
  tasks:
  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

- name: Copy join command to file
  hosts: master
  become: true
  tasks:
  - name: Copy join command to file
    copy:
      content: "{{ join_command.stdout_lines[0] }}"
      dest: /home/kube/joincommand.sh

- name: Copy join command to ansible host
  hosts: master
  become: true
  tasks:
  - name: Copy join command to ansible host
    fetch:
      src: /home/kube/joincommand.sh
      dest: /home/kube/
      flat: yes

- name: Copy the join command to workers
  hosts: worker
  become: true
  tasks:
  - name: Copy the join command to workers
    copy:
      src: /home/kube/joincommand.sh
      dest: /home/kube/
      owner: kube
      group: kube
      mode: '0777'

#- name: Copy the join command to workers
#  hosts: worker
#  become: true
#  tasks:
#  - name: Copy the join command to workers
#    synchronize:
#      src: /home/kube/joincommand.sh
#      dest: /home/kube/
#    delegate_to: k8s-master

- name: Run the join command on workers
  hosts: worker
  become: true
  tasks:
  - name: Run the join command on workers
    command: sh /home/kube/joincommand.sh
